---
- name: Wait for VM and Cleanup
  hosts: all
  roles:
    - yaegashi.blockinfile
  vars_files:
    - vm_vars.yml
  handlers:
    - include: handlers/vmware.yml
  tasks:
    - name: Wait for CSR1000V to provision
      local_action: wait_for host={{ vm_ip_address }} port=22 delay=10 timeout=600
      sudo: false
    - name: Remove DHCP reservation
      blockinfile:
        dest: '{{ dhcpd_conf_path }}'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ vm_name }} {{ vm_ip_address }}"
        content: ""
      become: yes
      when: not vm_persist_dhcp_reservation
      notify:
        - stop vmware networking
        - start vmware networking