- name: Configure VMWare DHCP
  hosts: all
  roles:
    - yaegashi.blockinfile
  vars_files:
    - vm_vars.yml
  handlers:
    - include: handlers/vmware.yml
  tasks:
    - name: Remove previous DHCP reservations
      blockinfile:
        dest: '{{ dhcpd_conf_path }}'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ vm_name }} {{ vm_ip_address }}"
        content: ""
      become: yes
    - name: Add DHCP reservation
      blockinfile:
        dest: '{{ dhcpd_conf_path }}'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ vm_name }} {{ vm_ip_address }}"
        insertafter: EOF
        content: |
          host {{ vm_name }} {
            hardware ethernet {{ vm_mac_address }};
            fixed-address {{ vm_ip_address }};
            option domain-name-servers {{ vm_ip_gateway }};
            option domain-name localdomain;
            default-lease-time 1200;
            max-lease-time 1200;  
            option routers {{ vm_ip_gateway }};
          }
      become: yes
      notify:
        - stop vmware networking
        - start vmware networking