---
- name: Introspect Virtual Machine information
  hosts: all
  vars_files:
    - vm_vars.yml
  handlers:
    - include: handlers/vmware.yml
  tasks:
    - name: Configure management interface as Share with my Mac
      lineinfile: >
        dest='{{ vm_vmx_path }}'
        regexp='^ethernet{{vm_mgmt_interface}}.connectionType ='
        line='ethernet{{vm_mgmt_interface}}.connectionType = "nat"'
      notify:
        - start vm
        - stop vm
    - meta: flush_handlers
    - name: Get vmnet8 IP address
      shell: ifconfig vmnet8 | awk '/inet/{print $2}'
      register: vmnet8_ip_address
      changed_when: False
    - name: Get Management interface MAC address
      shell: cat '{{ vm_vmx_path }}' | awk -F'"' '/ethernet{{ vm_mgmt_interface }}.generatedAddress = /{print $2}'
      register: vm_mac_address
      changed_when: False
    - name: Set VM MAC access fact
      set_fact: vm_mac_address={{ vm_mac_address.stdout }}
    - name: Set VM IP address fact
      set_fact: vm_ip_address={{ vmnet8_ip_address.stdout | regex_replace(vm_mgmt_ip_regex_match, vm_mgmt_ip_regex_replace) }}
    - name: Set VM IP gateway fact
      set_fact: vm_ip_gateway={{ vmnet8_ip_address.stdout | regex_replace(vm_mgmt_ip_regex_match, vm_mgmt_gateway_regex_replace) }}