---
- name: Wait for CSR1000V to provision
  local_action: wait_for host={{ csr_vm_ip_address }} port=22 delay=10 timeout=600
  sudo: false
- name: Remove DHCP reservation
  blockinfile:
    dest: '{{ csr_dhcpd_conf_path }}'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ csr_vm_name }} {{ csr_vm_ip_address }}"
    content: ""
  become: yes
  when: not csr_vm_persist_dhcp_reservation
  notify:
    - stop vmware networking
    - start vmware networking