---
- name: Add entry to hosts file
  lineinfile: 
    dest: /etc/hosts
    line: '{{ csr_vm_ip_address }} {{ csr_vm_name }}'
    regexp: '{{ csr_vm_name }}$'
    insertafter: EOF
  when: csr_vm_persist_dhcp_reservation
  become: yes