---
- name: Configure management interface as Share with my Mac
  lineinfile: >
    dest='{{ csr_vm_vmx_path }}'
    regexp='^ethernet{{ csr_vm_mgmt_interface }}.connectionType ='
    line='ethernet{{ csr_vm_mgmt_interface }}.connectionType = "nat"'
  notify:
    - start vm headless
    - stop vm
- meta: flush_handlers
- name: Get vmnet8 IP address
  shell: ifconfig vmnet8 | awk '/inet/{print $2}'
  register: csr_vmnet8_ip_address
  changed_when: False
- name: Get Management interface MAC address
  shell: cat '{{ csr_vm_vmx_path }}' | awk -F'"' '/ethernet{{ csr_vm_mgmt_interface }}.generatedAddress = /{print $2}'
  register: csr_vm_mac_address
  changed_when: False
- name: Set VM MAC access fact
  set_fact: csr_vm_mac_address={{ csr_vm_mac_address.stdout }}
- name: Set VM IP address fact
  set_fact: csr_vm_ip_address={{ csr_vmnet8_ip_address.stdout | regex_replace(csr_vm_mgmt_ip_regex_match, csr_vm_mgmt_ip_regex_replace) }}
- name: Set VM IP gateway fact
  set_fact: csr_vm_ip_gateway={{ csr_vmnet8_ip_address.stdout | regex_replace(csr_vm_mgmt_ip_regex_match, csr_vm_mgmt_gateway_regex_replace) }}