---
- name: stop vmware networking
  command: '"{{ vmnet_path }}" --stop'
  become: yes
- name: start vmware networking
  command: '"{{ vmnet_path }}" --start'
  become: yes
- name: start vm
  command: '"{{ vmrun_path }}" start "{{ vm_vmx_path }}"'
  become: yes
- name: stop vm
  command: '"{{ vmrun_path }}" stop "{{ vm_vmx_path }}"'
  become: yes